name: ${DOCKER_PROD_NAME}

services:
  express:
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile
    ports:
      - '${DOCKER_PROD_EXPRESS_PORT}:5000'
    restart: unless-stopped
    init: true