name: ${DOCKER_DEV_NAME}

services:
  nuxt:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ../../:/app
    ports:
      - '${DOCKER_DEV_NUXT_PORT}:5173'
    command: bash -c "bun install && bun run dev"
    init: true
