name: ${DOCKER_PROD_NAME}

services:
  nuxt:
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile
    volumes:
      - ../../dist:/dist # The volume to store the built files
    command: sh -c "cp -r /app/.output/public/. /dist/"